[package]
name = "sunrs"
version = "0.1.0"
authors = ["Tim Deve <timdeve@users.noreply.github.com>"]
edition = "2018"

[dependencies]
bincode = "1.2"
c2rust-bitfields="0.3.0"
libc = "0.2.67"
hex = "0.4.2"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
