[bulbs]
bulb-one = "D0:73:D5:00:00:01"
bulb-two = "D0:73:D5:00:00:02"

[[scenes]]
name = "Daylight"
command = "day"

  [[scenes.values]]
  bulb = "bulb-one"
  brightness = 0xFFFF
  kelvin = 5000

  [[scenes.values]]
  bulb = "bulb-two"
  brightness = 0xFFFF
  kelvin = 5000

[[scenes]]
name = "Reading"
command = "read"

  [[scenes.values]]
  bulb = "bulb-one"
  brightness = 0x0000
  kelvin = 400

  [[scenes.values]]
  bulb = "bulb-two"
  brightness = 0xFFFF
  kelvin = 400

